module.exports = {
  "United Kingdom": 1,
  "Albania": 0,
  "Algeria": 0,
  "Andorra": 0,
  "Angola ": 0,
  "Anguilla ": 0,
  "Antigua and Barbuda": 0,
  "Argentina": 0,
  "Armenia": 0,
  "Aruba": 0,
  "Australia": 0,
  "Austria": 1,
  "Azerbaijan Republic": 0,
  "Bahamas": 0,
  "Bahrain": 0,
  "Barbados ": 0,
  "Belgium": 1,
  "Belize ": 0,
  "Benin": 0,
  "Bermuda": 0,
  "Bhutan ": 0,
  "Bolivia": 0,
  "Bosnia and Herzegovina ": 0,
  "Botswana ": 0,
  "Brazil ": 0,
  "Brunei ": 0,
  "Bulgaria ": 1,
  "Burkina": 0,
  "Burundi": 0,
  "Cambodia ": 0,
  "Canada ": 0,
  "Cape Verde ": 0,
  "Cayman Islands ": 0,
  "Chad ": 0,
  "Chile": 0,
  "China": 0,
  "Colombia ": 0,
  "Comoros": 0,
  "Cook Islands ": 0,
  "Costa Rica ": 0,
  "Croatia": 0,
  "Cyprus ": 1,
  "Czech Republic ": 0,
  "Democratic Republic of the Congo ": 0,
  "Denmark": 1,
  "Djibouti ": 0,
  "Dominica ": 0,
  "Dominican Republic ": 0,
  "Ecuador": 0,
  "El Salvador": 0,
  "Eritrea": 0,
  "Estonia": 1,
  "Ethiopia ": 0,
  "Falkland Islands ": 0,
  "Faroe Islands": 0,
  "Fiji ": 0,
  "Finland": 1,
  "France ": 1,
  "French Guiana": 0,
  "French Polynesia ": 0,
  "Gabon": 0,
  "Republic Gambia": 0,
  "Germany": 1,
  "Gibraltar": 0,
  "Greece ": 1,
  "Greenland": 0,
  "Grenada": 0,
  "Guadeloupe ": 0,
  "Guatemala": 0,
  "Guinea ": 0,
  "Guinea Bissau": 0,
  "Guyana ": 0,
  "Honduras ": 0,
  "HongHong ": 0,
  "Hungary": 1,
  "Iceland": 0,
  "India": 0,
  "Indonesia": 0,
  "Ireland": 1,
  "Israel ": 0,
  "Italy": 1,
  "Jamaica": 0,
  "Japan": 0,
  "Jordan ": 0,
  "Kazakhstan ": 0,
  "Kenya": 0,
  "Kiribati ": 0,
  "Kuwait ": 0,
  "Kyrgyzstan ": 0,
  "LaosLatvia ": 0,
  "Lesotho": 0,
  "Liechtenstein": 0,
  "Lithuania": 1,
  "Luxembourg ": 1,
  "Madagascar ": 0,
  "Malawi ": 0,
  "Malaysia ": 0,
  "Maldives ": 0,
  "Mali ": 0,
  "Malta": 1,
  "MarshallIslands": 0,
  "Martinique ": 0,
  "Mauritania ": 0,
  "Mauritius": 0,
  "Mayotte": 0,
  "Mexico ": 0,
  "Micronesia ": 0,
  "Mongolia ": 0,
  "Montserrat ": 0,
  "Morocco": 0,
  "Mozambique ": 0,
  "Namibia": 0,
  "Nauru": 0,
  "Nepal": 0,
  "Netherlands": 1,
  "Antilles ": 0,
  "New Caledonia": 0,
  "New Zealand": 0,
  "Nicaragua": 0,
  "Niger": 0,
  "Niue ": 0,
  "Norfolk Island ": 0,
  "Norway ": 0,
  "Oman ": 0,
  "Palau": 0,
  "Panama ": 0,
  "Papua New Guinea ": 0,
  "Peru ": 0,
  "Philippines": 0,
  "Pitcairn Islands ": 0,
  "Poland ": 1,
  "Portugal ": 1,
  "Qatar": 0,
  "Republic of the Congo": 0,
  "Reunion": 0,
  "Romania": 1,
  "Russia ": 0,
  "Rwanda ": 0,
  "Saint Kitts and Nevis Anguilla ": 0,
  "Saint Pierre and Miquelon": 0,
  "Saint Vincent and Grenadines ": 0,
  "Samoa": 0,
  "San Marino ": 0,
  "Saudi Arabia ": 0,
  "Senegal": 0,
  "Seychelles ": 0,
  "Sierra Leone ": 0,
  "Singapore": 0,
  "Slovakia ": 1,
  "Slovenia ": 1,
  "Solomon Islands": 0,
  "Somalia": 0,
  "South Africa ": 0,
  "South Korea": 0,
  "Spain": 1,
  "Sri Lanka": 0,
  "St. Helena ": 0,
  "St. Lucia": 0,
  "Suriname ": 0,
  "Svalbard and Jan Mayen  Islands  ": 0,
  "Swaziland  ": 0,
  "Sweden ": 1,
  "Switzerland": 0,
  "Taiwan ": 0,
  "Tajikistan ": 0,
  "Tanzania ": 0,
  "Thailand ": 0,
  "Togo ": 0,
  "Tonga": 0,
  "Trinidad and Tobago": 0,
  "Tunisia": 0,
  "Turkey ": 0,
  "Turkmenistan ": 0,
  "Turks and Caicos Islands ": 0,
  "Tuvalu ": 0,
  "Uganda ": 0,
  "Ukraine": 0,
  "United Arab Emirates ": 0,
  "United States": 0,
  "Uruguay": 0,
  "Vanuatu": 0,
  "Vatican City State ": 0,
  "Venezuela": 0,
  "Vietnam": 0,
  "Virgin Islands (British) ": 0,
  "Wallis and Futuna Islands": 0,
  "Yemen": 0,
  "Zambia ": 0,
  "Latvia ": 1,
  "Czechia": 1
};
